arrowParens: always
bracketSpacing: true
bracketSameLine: true
jsxSingleQuote: false
printWidth: 120
endOfLine: auto
quoteProps: as-needed
semi: true
singleQuote: true
tabWidth: 2
trailingComma: es5
useTabs: true
