require('plugins.packer')

require('core.commands')
require('core.editor')
require('core.keymaps')
require('core.theme')

require('plugins.config.telescope')
require('plugins.config.null-ls')
require('plugins.config.lsp')
require('plugins.config.treesitter')
require('plugins.config.nvim-tree')
require('plugins.config.dashboard')
require('plugins.config.indent_blankline')
require('plugins.config.lualine')
