require 'plugins.packer'

require 'core.commands'
require 'core.editor'
require 'core.keymaps'
require 'core.theme'

require 'plugins.config.telescope'
require 'plugins.config.lsp'
require 'plugins.config.null-ls'
require 'plugins.config.treesitter'
require 'plugins.config.nvim-tree'
require 'plugins.config.dashboard'
require 'plugins.config.indent-blankline'
require 'plugins.config.lualine'
require 'plugins.config.cmp'
require 'plugins.config.nvim-autopairs'
require 'plugins.config.nvim-comment'
require 'plugins.config.gitsigns'
require 'plugins.config.tabby'
require 'plugins.config.colorizer'
require 'plugins.config.diagnostics'
require 'plugins.config.auto-session'
require 'plugins.config.rust-tools'
require 'plugins.config.vim-illuminate'
-- require('plugins.config.barbar')
